services:
  database:
    image: mariadb:12
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-fog}
      MARIADB_USER: ${MARIADB_USER:-fog}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-fog}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-fog}
  fog:
    image: fog
    #privileged: true # TODO: fixme
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      FOG_VERSION: 1.5.10.1870
      MARIADB_HOST: ${MARIADB_HOST:-database}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-fog}
      MARIADB_USER: ${MARIADB_USER:-fog}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-fog}
      WEB_USER: ${WEB_USER:-fog}
      WEB_PWD: ${WEB_PWD:-fog}
    ports:
      - "9445:80"

volumes:
  database:
