services:
  fog:
    image: cpasjuste/fog
    restart: unless-stopped
    privileged: true # for nfs-kernel-server
    environment:
      HTTP_ADDRESS: 192.168.0.83 # also used for tftp/nfs/... addresses
      # you can use a custom http port, but "Storage Node Disk Usage"
      # and "Bandwidth" graphs wont display correctly. 
      # this can be fixed with a reverse proxy (or use port 80)
      HTTP_PORT: ${HTTP_PORT:-80}
      WEB_PASSWORD: ${WEB_PASSWORD:-password} # for "fog" web user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dockerfogsql} # mysql user (fog) password
      STORAGE_PASSWORD: ${STORAGE_PASSWORD:-dockerfogstorage} # builtin storage (nfs/ftp/tftp...) password
    volumes:
      - database:/var/lib/mysql
      - /images:/images # on host: sudo mkdir /images && chown -R 1000:1000 /images
      - /lib/modules:/lib/modules:ro # for nfs-kernel-server
    ports:
      - "${HTTP_PORT:-80}:80" # web
      - "21:21"               # ftp
      - "111:111"             # nfs
      - "2049:2049"           # nfs
      - "20048:20048"         # nfs
      - "69:69/udp"           # tftp
volumes:
  database:
